server:
  servlet:
    encoding:
      force: true

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/bookshop"
    username: "postgres"
    password: "TheWitcher3"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update